package cliente;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.net.InetAddress;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import rmi.ServerInterface;
import java.rmi.registry.*;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import rmi.Result;
import rmi.User;

/// Referencias
/// Dialogo -> https://docs.oracle.com/javase/tutorial/uiswing/components/dialog.html
/// Seletor de ficheiros -> https://www.rgagnon.com/javadetails/java-0370.html
/// Listagem de ficheiros -> https://www.geeksforgeeks.org/list-all-files-from-a-directory-recursively-in-java/




public class App extends javax.swing.JFrame {

    private String ip;
    private String username;
    private File sharedFolder;
    private ServerInterface serverInterface;
    private List<User> users;
    private LogsThread logsThread;
    private boolean loggedIn = false;

    public App() {
        initComponents();

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Call your function or logic to decide whether to close
                try {
                    Result result = serverInterface.logout(username);
                    loggedIn = false;
                    logsThread.kill();
                    username = null;
                    sessionButton.setText("Login");
                    selectFolderButton.setEnabled(true);
                    ipField.setEnabled(true);
                    portField.setEnabled(true);
                    usernameField.setEnabled(true);
                } catch (Exception exception) {
                    exception.printStackTrace();
                }
            }
        });

        try {
            String hostname = InetAddress.getLocalHost().getHostName();
            usernameField.setText(hostname);

            clientsList.addListSelectionListener((ListSelectionEvent e) -> {
                if (!e.getValueIsAdjusting()) {
                    JList<String> list = (JList<String>) e.getSource();
                    String selectedUsername = list.getSelectedValue();

                    for (User user : users) {
                        if (user.getUserName().equals(selectedUsername)) {

                            DefaultListModel<String> listModel = new DefaultListModel<>();

                            user.getFiles().forEach(path -> {
                                File file = new File(path);
                                listModel.addElement(file.getName());
                            });

                            filesList.setModel(listModel);

                            break;
                        }
                    }
                }
            });

            filesList.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    System.out.println(e.getClickCount());
                }
            });

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        labelClientes = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        clientsList = new javax.swing.JList<>();
        labelConfiguracoes = new javax.swing.JLabel();
        labelFicheiros = new javax.swing.JLabel();
        ipField = new javax.swing.JTextField();
        labelServidor = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        labelPasta = new javax.swing.JLabel();
        labelPastaPartilhada = new javax.swing.JLabel();
        sessionButton = new javax.swing.JButton();
        selectFolderButton = new javax.swing.JButton();
        labelFicheiros1 = new javax.swing.JLabel();
        labelServidor1 = new javax.swing.JLabel();
        portField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        filesList = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        logsList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente");
        setResizable(false);

        labelClientes.setText("Clientes");

        clientsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(clientsList);

        labelConfiguracoes.setFont(new java.awt.Font("Inter Display", 1, 18)); // NOI18N
        labelConfiguracoes.setText("Configurações");

        labelFicheiros.setText("Ficheiros");

        ipField.setText("192.168.18.59");

        labelServidor.setFont(new java.awt.Font("Inter Display", 1, 15)); // NOI18N
        labelServidor.setText("Endereço Servidor");

        labelUsername.setFont(new java.awt.Font("Inter Display", 1, 15)); // NOI18N
        labelUsername.setText("Username");

        labelPasta.setText("Nenhuma pasta selecionada");

        labelPastaPartilhada.setFont(new java.awt.Font("Inter Display", 1, 15)); // NOI18N
        labelPastaPartilhada.setText("Pasta Partilhada");

        sessionButton.setText("Login");
        sessionButton.setEnabled(false);
        sessionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sessionButtonActionPerformed(evt);
            }
        });

        selectFolderButton.setText("Selecionar Pasta");
        selectFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFolderButtonActionPerformed(evt);
            }
        });

        labelFicheiros1.setText("Logs");

        labelServidor1.setFont(new java.awt.Font("Inter Display", 1, 15)); // NOI18N
        labelServidor1.setText("Porta");

        portField.setText("1099");
        portField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portFieldActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(filesList);

        jScrollPane4.setViewportView(logsList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelConfiguracoes)
                        .addGap(519, 519, 519))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelClientes))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelFicheiros)
                                    .addGap(405, 405, 405))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane2)
                                    .addGap(6, 6, 6))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelUsername)
                                .addComponent(sessionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ipField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelServidor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelServidor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelPastaPartilhada)
                                    .addComponent(labelPasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(selectFolderButton))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFicheiros1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelClientes)
                    .addComponent(labelFicheiros)
                    .addComponent(labelFicheiros1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(labelConfiguracoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelServidor)
                            .addComponent(labelServidor1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ipField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPastaPartilhada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPasta)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(selectFolderButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sessionButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFolderButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Selecione uma pasta para partilhar");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            sharedFolder = chooser.getSelectedFile();
            labelPasta.setText(sharedFolder.toString());

            sessionButton.setEnabled(true);
        }
    }//GEN-LAST:event_selectFolderButtonActionPerformed

    private void sessionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sessionButtonActionPerformed
        try {

            if (loggedIn == false) {

                ip = ipField.getText();
                username = usernameField.getText();

                Registry registry = LocateRegistry.getRegistry(ip, 1099);
                serverInterface = (ServerInterface) registry.lookup("projeto-sd");

                List<String> files = new ArrayList<>();

                Files.newDirectoryStream(sharedFolder.toPath()).forEach(path -> {
                    if (new File(path.toString()).isFile()) {
                        files.add(path.toString());
                    }
                });

                Result loginResult = serverInterface.login(username, sharedFolder.getAbsolutePath(), files);

                if (!loginResult.getSuccess()) {
                    JOptionPane.showMessageDialog(this,
                            loginResult.getMessage(),
                            "Erro",
                            JOptionPane.ERROR_MESSAGE);

                    return;
                }

                users = serverInterface.getUsers();

                DefaultListModel<String> listModel = new DefaultListModel<>();

                users.forEach(user -> {
                    if (!user.getUserName().equals(username)) {
                        listModel.addElement(user.getUserName());
                    }
                });

                clientsList.setModel(listModel);

                sessionButton.setText("Logout");
                selectFolderButton.setEnabled(false);
                ipField.setEnabled(false);
                portField.setEnabled(false);
                usernameField.setEnabled(false);
                loggedIn = true;

                logsThread = new LogsThread(serverInterface, username, logsList);
                Thread thread = new Thread(logsThread);
                thread.start();

            } else {
                Result result = serverInterface.logout(username);
                loggedIn = false;
                logsThread.kill();
                username = null;
                sessionButton.setText("Login");
                selectFolderButton.setEnabled(true);
                ipField.setEnabled(true);
                portField.setEnabled(true);
                usernameField.setEnabled(true);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_sessionButtonActionPerformed

    private void portFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> clientsList;
    private javax.swing.JList<String> filesList;
    private javax.swing.JTextField ipField;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelClientes;
    private javax.swing.JLabel labelConfiguracoes;
    private javax.swing.JLabel labelFicheiros;
    private javax.swing.JLabel labelFicheiros1;
    private javax.swing.JLabel labelPasta;
    private javax.swing.JLabel labelPastaPartilhada;
    private javax.swing.JLabel labelServidor;
    private javax.swing.JLabel labelServidor1;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JList<String> logsList;
    private javax.swing.JTextField portField;
    private javax.swing.JButton selectFolderButton;
    private javax.swing.JButton sessionButton;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables

}
